name: product_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.4
  http: ^0.13.5
  image_cropper: ^3.0.3
  image_picker: ^0.8.7+4
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
