// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiGYZOWEZXU6knnfeFUjHXF5bXKG9yVe8',
    appId: '1:575509751740:web:9b63e87c4700f5ecd66db9',
    messagingSenderId: '575509751740',
    projectId: 'geolocation-bloc',
    authDomain: 'geolocation-bloc.firebaseapp.com',
    storageBucket: 'geolocation-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa-8pHGPk3010eEiFt-X47Me07ckoDfPE',
    appId: '1:575509751740:android:a040a6f5fe721f26d66db9',
    messagingSenderId: '575509751740',
    projectId: 'geolocation-bloc',
    storageBucket: 'geolocation-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBylIm4ZcE5Nh8pW6Tt_A_hgFoSVG5um0M',
    appId: '1:575509751740:ios:af9038a670063f43d66db9',
    messagingSenderId: '575509751740',
    projectId: 'geolocation-bloc',
    storageBucket: 'geolocation-bloc.appspot.com',
    iosClientId: '575509751740-oju3isbho3kvdmnsvs736laq351am2og.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapsBloc',
  );
}
