// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOxsma_2uHb8hCagn3onzkoqW-ohWL9qc',
    appId: '1:990822151219:web:a82c9f26a31313e8c81f46',
    messagingSenderId: '990822151219',
    projectId: 'myfirst-bloc',
    authDomain: 'myfirst-bloc.firebaseapp.com',
    storageBucket: 'myfirst-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZjaE2M8LOvscD8fHCEq4lYOm8yGUorU',
    appId: '1:990822151219:android:5ae7c6cc3d97f4a3c81f46',
    messagingSenderId: '990822151219',
    projectId: 'myfirst-bloc',
    storageBucket: 'myfirst-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMZe7U-T0rnEL61XkdatrQMS7b8ula6VA',
    appId: '1:990822151219:ios:6edb39bf22b1f70fc81f46',
    messagingSenderId: '990822151219',
    projectId: 'myfirst-bloc',
    storageBucket: 'myfirst-bloc.appspot.com',
    iosBundleId: 'com.example.myAppBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMZe7U-T0rnEL61XkdatrQMS7b8ula6VA',
    appId: '1:990822151219:ios:58a76f1ca4acb2fdc81f46',
    messagingSenderId: '990822151219',
    projectId: 'myfirst-bloc',
    storageBucket: 'myfirst-bloc.appspot.com',
    iosBundleId: 'com.example.myAppBloc.RunnerTests',
  );
}
